Adds code for testing if a VID is a member of a sampling bucket.
world-federation-of-advertisers/any-sketch-java pull request #8
Opened 2022-02-11 03:07 UTC by matthewclegg

2022-02-11 18:50 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: all files reviewed, 8 unresolved discussions (waiting on @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve2BKo6-08Ivz68wL8:-Mve2BKo6-08Ivz68wL9:b-nogmb1) (no related file):*
nit: PR subject (first line of merge message) should be an imperative sentence ("**Add** code for...")

---
___
*[.bazelversion, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve2merEkFjF-g4lBFz:-Mve2merEkFjF-g4lBG-:b8uroxo) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/.bazelversion#L1)):*
> ```
> 4.2.1
> ```

nit: 4.2.2 has been released. By SemVer, it's just a bugfix release with no incompatible changes so should be safe to specify.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve3HhK4jqfV4CTytH7:-Mve3HhK4jqfV4CTytH8:bniwq02) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L1)):*
> ```Java
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Is this file a copy of one that was written in 2020? If not, this should likely be the current year.



_Code quote:_
```Java
2020
```
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve4pI5Bcbd1tJaJsUL:-Mve4pI5Bcbd1tJaJsUM:begceqk) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L35)):*
> ```Java
>   private final double maskDivisor = 1.0 / (double) Ieee754MantissaMask;
> 
>   /** Hashes a vid to a real number in the interval [0, 1]. */
> ```

nit: be consistent with casing in comments/documentation. I assume this should be `VID`.



_Code quote:_
```Java
vid
```
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve4z4g62LP1jr2nY2n:-Mve4z4g62LP1jr2nY2o:b-of38ld) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
> ```Java
> 
>   /** Hashes a vid to a real number in the interval [0, 1]. */
>   public double hashVidToUnitInterval(Long vid) {
> ```

Are we expecting `null` as a possible value here? If not, this should probably be `long` rather than `Long`.



_Code quote:_
```Java
Long
```
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve58g87c4JWfRrYq-Q:-Mve58g87c4JWfRrYq-R:b-j2mq4o) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L56)):*
> ```Java
>    */
>   public boolean vidIsInSamplingBucket(
>       Long vid, Float samplingIntervalStart, Float samplingIntervalWidth) {
> ```

Same here re: nullable boxed types



_Code quote:_
```Java
Long vid, Float samplingIntervalStart, Float samplingIntervalWidth
```
___
*[src/test/java/org/wfanet/sampling/BUILD.bazel, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve5f8Q9pCBddcLQeK6:-Mve5f8Q9pCBddcLQeK7:b-sa0f3n) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/test/java/org/wfanet/sampling/BUILD.bazel#L8)):*
nit: I *think* our folder hierarchy means that Bazel should find this test class on its own and therefore it doesn't need to be specified.

From https://docs.bazel.build/versions/4.2.2/be/java.html#java_test.test_class:
> It is rare to need to set this. If this argument is omitted, it will be inferred using the target's name and its source-root-relative path.

Note that this doesn't work for our Kotlin code in our other repos, as it uses Java logic underneath and therefore looks for an ancestor folder named `java`.
___
*[src/test/java/org/wfanet/sampling/VidSamplingBucketTesterTest.java, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve6ila9OKxc_DYrI5D:-Mve6ila9OKxc_DYrI5E:b-uvp7hb) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/test/java/org/wfanet/sampling/VidSamplingBucketTesterTest.java#L19)):*
> ```Java
> import static org.junit.Assert.assertEquals;
> import static org.junit.Assert.assertFalse;
> import static org.junit.Assert.assertTrue;
> ```

Use Truth.



_Code quote:_
```Java
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
```


<!-- Sent from Reviewable.io -->

2022-02-14 21:55 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve4z4g62LP1jr2nY2n:-MvuCnVlDWa-NtEZA3yL:b-jmrnw4) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I agree with you here.  It was initially long but the Java formatter changed it to Long.  I have changed it back to long.
</blockquote></details>

I ran google-java-format on this file and it didn't detect any formatting changes needed.


<!-- Sent from Reviewable.io -->

2022-02-14 23:31 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve4z4g62LP1jr2nY2n:-MvuZfIk52ANkN5AStDE:boky691) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I ran google-java-format on this file and it didn't detect any formatting changes needed.
</blockquote></details>

That's odd.  Maybe I'm losing it.


<!-- Sent from Reviewable.io -->

2022-02-15 16:35 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: all files reviewed, 10 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyE6Tb11H3oF-zm1-0:-MvyE6TcA2nPg1bMGXov:b-ts2zpx) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L29)):*
> ```Java
> 
>   // The mantissa of an IEEE 754 double is 52 bits.
>   private final long Ieee754MantissaMask = 0xf_ffff_ffff_ffffL;
> ```

Should be static.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyEANsCtYr4-9njY59:-MvyEANsCtYr4-9njY5A:b-ts2zpx) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L33)):*
> ```Java
>   // A divisor that is used to convert the lower 52 bits of the
>   // fingerprinted value to a floating point value between 0 and 1.
>   private final double maskDivisor = 1.0 / (double) Ieee754MantissaMask;
> ```

Should be static.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyEEPXCGHHjwrx3wHJ:-MvyEEPXCGHHjwrx3wHK:bze479v) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
> ```Java
> 
>   /** Hashes a vid to a real number in the interval [0, 1]. */
>   public double hashVidToUnitInterval(long vid) {
> ```

Static
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyEG1v4c3YY2d7SEkU:-MvyEG1v4c3YY2d7SEkV:bze479v) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L55)):*
> ```Java
>    * @return True if the hashed VID is in the interval from samplingIntervalStart
>    */
>   public boolean vidIsInSamplingBucket(
> ```

Static


<!-- Sent from Reviewable.io -->

2022-02-15 22:08 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 1 of 5 files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @kungfucraig, and @SanjayVas)

___
*[.bazelversion, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyBlXX-4tiPPe2ANqY:-MvyxbBJ0Flw1FBbsuN2:b3sm9oj) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/.bazelversion#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

Evidently much of the any-sketch-java library no longer builds and runs without this.  As an example, try the following:

```
bazel test src/test/java/org/wfanet/estimation:value_histogram_test
```

Yao can provide you with more details.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyC2AjDjMVX4J2F3ps:-MvyyLfd7AafJkKrUvn6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please rename this class to something like "VidSampler" or "VidBucketFilter" or "VidSamplingBucketFilter". Have "Tester" in the name is confusing.
</blockquote></details>

Done.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyE6Tb11H3oF-zm1-0:-MvyyW705n8-EH8KsE2U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L29)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should be static.
</blockquote></details>

Done.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyEANsCtYr4-9njY59:-MvyyWdRC1B88ath8djd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L33)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should be static.
</blockquote></details>

Done.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDa0Q6EvetuTzd6Mo:-MvyyX3O2w8Fou4nZmAR:bkqzy0l) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why doubles?
</blockquote></details>

No particular reason.  Would you prefer something else?
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyEEPXCGHHjwrx3wHJ:-MvyycIG4JqoRQ1gBPTH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Static
</blockquote></details>

Done.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDh6pDvr8OzzwXEkh:-MvyytzK0sn0X8or-vC-:b-dpitrv) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L41)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I feel like we decided to use SHA256 for these types of things, but I'm not entirely sure.  Check with @efoxepstein ?
</blockquote></details>

Eli is on paternity leave.  Please advise.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyEG1v4c3YY2d7SEkU:-MvyzLsl36hO9yRRQMJA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L55)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Static
</blockquote></details>

Done.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyCkUCCfcFb-Fm-z-J:-MvyzSNJ9fKVbIeXQ3mz:bjpsvqh) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L57)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why boxed?
</blockquote></details>

Changed to double.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDKfK4QMvWVHMdg3v:-Mvyzu9o07X3tDm6W1uf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L59)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Have a temporary for samplingIntervalEnd instead of calculating it twice?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 22:30 UTC, kungfucraig requested changes
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDa0Q6EvetuTzd6Mo:-MvzUuSfCudCuoI9YAD2:bn837z) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

No particular reason.  Would you prefer something else?
</blockquote></details>

If a float will suffice then it will be the same as the interval specification. The discrepancy in type between the interval and the return types of these functions was just a head scratcher for me. I assumed it was purposeful. :)
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDh6pDvr8OzzwXEkh:-MvzVGtwBKGSDLUrz8A5:b-wv0wh9) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L41)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Eli is on paternity leave.  Please advise.
</blockquote></details>

@sanjayvas WDYT?

Arguably making this method non-static and passing the hasher as a constructor parameter could have some benefits both for this conversation and for testability.


<!-- Sent from Reviewable.io -->

2022-02-15 22:45 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @SanjayVas)

___
*[.bazelversion, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyBlXX-4tiPPe2ANqY:-MvzYLyC1SS2cN3W3Suy:b-8tqxa3) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/.bazelversion#L1)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Evidently much of the any-sketch-java library no longer builds and runs without this.  As an example, try the following:

```
bazel test src/test/java/org/wfanet/estimation:value_histogram_test
```

Yao can provide you with more details.
</blockquote></details>

This file indicates which Bazel version to use for this workspace. This is particularly useful given that Bazel has been pushing major versions with incompatible changes. For those of us running managed workstations (e.g. at Google), our machines automatically update to the latest version of Bazel.

This file is read by the Bazelisk launcher for Bazel. See https://docs.bazel.build/versions/4.2.2/install-bazelisk.html


<!-- Sent from Reviewable.io -->

2022-02-15 23:01 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mvz_gOo5GP7J3Wl_X5s:-Mvz_gOo5GP7J3Wl_X5t:b-v4vbz2) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/106c8f7b9faa7f1320c73b1bacb183b20fb5a275/src/main/java/org/wfanet/sampling/VidSampler.java#L23)):*
> ```Java
>  * Filter VIDs by sampling bucket.
>  *
>  * <p>NOTE: IT IS IMPORTANT THAT ALL EDPS USE THE SAME METHOD FOR HASHING VIDS TO THE UNIT INTERVAL.
> ```

Can you be more specific? e.g. Is this all EDPs using a given VID model? All EDPs that are labeling events to the same Kingdom? etc.



_Code quote:_
```Java
ALL EDPS
```
___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvzaG7p0KlAsjjw2cLJ:-MvzaG7p0KlAsjjw2cLK:bjukv70) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/106c8f7b9faa7f1320c73b1bacb183b20fb5a275/src/main/java/org/wfanet/sampling/VidSampler.java#L26)):*
> ```Java
>  * DO NOT CHANGE OR MODIFY THE WAY THAT HASH VALUES ARE COMPUTED.
>  */
> public class VidSampler {
> ```

If this is a utility class with only static members, then it should not be instantiable. This can be done by marking the class as abstract and making its default and only constructor private.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDh6pDvr8OzzwXEkh:-MvzZ9J18sp-BAaTv5pa:bb4f2ap) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L41)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@sanjayvas WDYT?

Arguably making this method non-static and passing the hasher as a constructor parameter could have some benefits both for this conversation and for testability.
</blockquote></details>

I know we decided to shift most general hashes to use SHA256 by default, though it appears AnySketch appears to include Farmhash as its [default Fingerprinter implementation](https://github.com/world-federation-of-advertisers/any-sketch-java/tree/main/src/main/java/org/wfanet/anysketch/fingerprinters). I wasn't part of this decision, so I don't know if we intended to switch AnySketch away from Farmhash or to continue to use it as a faster non-cryptographic hash.

If we want the hash function to be configurable (with the documented caveat that it must be the same for some set of users), then that should be a constructor param (meaning that VidSampler should go back to being instantiable rather than a utility class).


<!-- Sent from Reviewable.io -->

2022-02-16 00:24 UTC, kungfucraig requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDh6pDvr8OzzwXEkh:-MvzuZd2-tDVLo2NW3LP:bcq1ih) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I know we decided to shift most general hashes to use SHA256 by default, though it appears AnySketch appears to include Farmhash as its [default Fingerprinter implementation](https://github.com/world-federation-of-advertisers/any-sketch-java/tree/main/src/main/java/org/wfanet/anysketch/fingerprinters). I wasn't part of this decision, so I don't know if we intended to switch AnySketch away from Farmhash or to continue to use it as a faster non-cryptographic hash.

If we want the hash function to be configurable (with the documented caveat that it must be the same for some set of users), then that should be a constructor param (meaning that VidSampler should go back to being instantiable rather than a utility class).
</blockquote></details>

I like the idea of being able to pass the hasher into the constructor. Then we can punt this decision here. :)


<!-- Sent from Reviewable.io -->

2022-02-16 02:31 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @kungfucraig, and @SanjayVas)

___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mvz_gOo5GP7J3Wl_X5s:-Mw-LDvmCl_H6REfnM1y:b-xszk4q) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/106c8f7b9faa7f1320c73b1bacb183b20fb5a275/src/main/java/org/wfanet/sampling/VidSampler.java#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you be more specific? e.g. Is this all EDPs using a given VID model? All EDPs that are labeling events to the same Kingdom? etc.
</blockquote></details>

I have updated the comment.  Let me know if you prefer this verbiage.
___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvzaG7p0KlAsjjw2cLJ:-Mw-LJK15yOs5JCa-eN2:bqgv43o) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/106c8f7b9faa7f1320c73b1bacb183b20fb5a275/src/main/java/org/wfanet/sampling/VidSampler.java#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this is a utility class with only static members, then it should not be instantiable. This can be done by marking the class as abstract and making its default and only constructor private.
</blockquote></details>

Thank you for explaining that.  This comment is no longer relevant since the class is no longer purely a utility class.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDa0Q6EvetuTzd6Mo:-Mw-Kq5-BivkvNeybyo7:b-qp3sbh) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If a float will suffice then it will be the same as the interval specification. The discrepancy in type between the interval and the return types of these functions was just a head scratcher for me. I assumed it was purposeful. :)
</blockquote></details>

I have changed the data type to float throughout.
___
*[src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-MvyDh6pDvr8OzzwXEkh:-Mw-KzNE40ddReJitlFi:b-zadntt) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/b748792d24c57125ee6f1a3d9e3773bedec49091/src/main/java/org/wfanet/sampling/VidSamplingBucketTester.java#L41)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I like the idea of being able to pass the hasher into the constructor. Then we can punt this decision here. :)
</blockquote></details>

I have added a constructor with a hasher as an argument.


<!-- Sent from Reviewable.io -->

2022-02-16 18:36 UTC, SanjayVas approved these changes
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @kungfucraig)

___
*[src/test/java/org/wfanet/sampling/BUILD.bazel, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve5f8Q9pCBddcLQeK6:-Mw2oKI8Cl9fhIJ-ffOw:bd0jqjv) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/test/java/org/wfanet/sampling/BUILD.bazel#L8)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I tried commenting out this line and `bazel test` failed.  So I guess it's necessary.  Maybe that's why this is also found in other previously existing unit tests in this repo?
</blockquote></details>

It isn't necessary if the target name matches the class test class name. If you name the test target `VidSamplerTest` instead of `tests`, then it should work.


<!-- Sent from Reviewable.io -->

2022-02-16 23:33 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg)

___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mw3ryXG50ySotPHwPpC:-Mw3ryXG50ySotPHwPpD:b-c6xix5) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/3b5536c41a9dc597d13bf1058968f674c374b2d2/src/main/java/org/wfanet/sampling/VidSampler.java#L26)):*
> ```Java
>  * BE COMBINED BY THE SMPC, INCLUDING THE CASE WHEN THOSE SKETCHES ARE COMPUTED BY DIFFERENT EDPS.
>  */
> public class VidSampler {
> ```

Mark final?
___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mw3rzoxCTXrDVOW82ZK:-Mw3rzoxCTXrDVOW82ZL:b-p1bogy) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/3b5536c41a9dc597d13bf1058968f674c374b2d2/src/main/java/org/wfanet/sampling/VidSampler.java#L36)):*
> ```Java
> 
>   // The hash function that will be used for this VidSampler.
>   private HashFunction hashFunction;
> ```

final? (I hate java)


<!-- Sent from Reviewable.io -->

2022-02-18 17:01 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/test/java/org/wfanet/sampling/BUILD.bazel, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mve5f8Q9pCBddcLQeK6:-MwCltqX3o16hjGb4AWz:bqmjy4j) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/94534d756577e86484565509d838de80bd1c3194/src/test/java/org/wfanet/sampling/BUILD.bazel#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It isn't necessary if the target name matches the class test class name. If you name the test target `VidSamplerTest` instead of `tests`, then it should work.
</blockquote></details>

I changed the target name to `VidSamplerTest` but  alas that did not solve the problem.
___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mw3ryXG50ySotPHwPpC:-MwClsGp36WNJyUVus5I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/3b5536c41a9dc597d13bf1058968f674c374b2d2/src/main/java/org/wfanet/sampling/VidSampler.java#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Mark final?
</blockquote></details>

Done.
___
*[src/main/java/org/wfanet/sampling/VidSampler.java, line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch-java/8#-Mw3rzoxCTXrDVOW82ZK:-MwClsp4E0AR5PP-oMLT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/3b5536c41a9dc597d13bf1058968f674c374b2d2/src/main/java/org/wfanet/sampling/VidSampler.java#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

final? (I hate java)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-18 17:03 UTC, merged